export const TILE_PARTS = {
  TOP_SIDE: 'TOP_SIDE',
  TOP_RIGHT_SIDE: 'TOP_RIGHT_SIDE',
  TOP_LEFT_SIDE: 'TOP_LEFT_SIDE',
  BOTTOM_SIDE: 'BOTTOM_SIDE',
  BOTTOM_RIGHT_SIDE: 'BOTTOM_RIGHT_SIDE',
  BOTTOM_LEFT_SIDE: 'BOTTOM_LEFT_SIDE'
}

export const TILE_COLORS = {
  PLAINS: '#A0DE7E',
  FIELD: '#e3ee55',
  QUARRY: '#404040',
  FORREST: '#06440a',
  BRICKYARD: '#773a18'
}