export const TILE_PARTS = {
  TOP_SIDE: 'TOP_SIDE',
  TOP_RIGHT_SIDE: 'TOP_RIGHT_SIDE',
  TOP_LEFT_SIDE: 'TOP_LEFT_SIDE',
  BOTTOM_SIDE: 'BOTTOM_SIDE',
  BOTTOM_RIGHT_SIDE: 'BOTTOM_RIGHT_SIDE',
  BOTTOM_LEFT_SIDE: 'BOTTOM_LEFT_SIDE'
}

export const TILE_COLORS = {
  PLAINS: '#A0DE7E',
  FIELD: '#f0f878ff',
  QUARRY: '#404040',
  FORREST: '#06440a',
  BRICKYARD: '#773a18',
  DESSERT: '#ffd900ff'
}

export const DEFAULT_TILES = [
  TILE_COLORS.FIELD, TILE_COLORS.FORREST, TILE_COLORS.PLAINS, TILE_COLORS.BRICKYARD, TILE_COLORS.QUARRY, TILE_COLORS.DESSERT,
  TILE_COLORS.FIELD, TILE_COLORS.FORREST, TILE_COLORS.PLAINS, TILE_COLORS.BRICKYARD, TILE_COLORS.QUARRY,
  TILE_COLORS.FIELD, TILE_COLORS.FORREST, TILE_COLORS.PLAINS, TILE_COLORS.BRICKYARD, TILE_COLORS.QUARRY,
  TILE_COLORS.FIELD, TILE_COLORS.FORREST, TILE_COLORS.PLAINS
]