export const TILE_EDGES = {
  RIGHT_SIDE: "RIGHT_SIDE",
  TOP_RIGHT_SIDE: "TOP_RIGHT_SIDE",
  TOP_LEFT_SIDE: "TOP_LEFT_SIDE",
  LEFT_SIDE: "LEFT_SIDE",
  BOTTOM_RIGHT_SIDE: "BOTTOM_RIGHT_SIDE",
  BOTTOM_LEFT_SIDE: "BOTTOM_LEFT_SIDE",
} as const;
export type TileEdgeNames = (typeof TILE_EDGES)[keyof typeof TILE_EDGES];

export const TILE_VERTICES = {
  VERTEX_TWELVE: "VERTEX_TWELVE",
  VERTEX_TWO: "VERTEX_TWO",
  VERTEX_FOUR: "VERTEX_FOUR",
  VERTEX_SIX: "VERTEX_SIX",
  VERTEX_EIGHT: "VERTEX_EIGHT",
  VERTEX_TEN: "VERTEX_TEN",
} as const;
export type TileVertexNames = (typeof TILE_VERTICES)[keyof typeof TILE_VERTICES];

export const TILE_COLORS = {
  PLAINS: "#A0DE7E",
  FIELD: "#F0F878",
  QUARRY: "#404040",
  FORREST: "#06440A",
  BRICKYARD: "#773A18",
  DESSERT: "#FFD900",
} as const;
export type TileColorType = (typeof TILE_COLORS)[keyof typeof TILE_COLORS];

export const DEFAULT_TILES = [
  TILE_COLORS.FIELD,
  TILE_COLORS.FORREST,
  TILE_COLORS.PLAINS,
  TILE_COLORS.BRICKYARD,
  TILE_COLORS.QUARRY,
  TILE_COLORS.DESSERT,
  TILE_COLORS.FIELD,
  TILE_COLORS.FORREST,
  TILE_COLORS.PLAINS,
  TILE_COLORS.BRICKYARD,
  TILE_COLORS.QUARRY,
  TILE_COLORS.FIELD,
  TILE_COLORS.FORREST,
  TILE_COLORS.PLAINS,
  TILE_COLORS.BRICKYARD,
  TILE_COLORS.QUARRY,
  TILE_COLORS.FIELD,
  TILE_COLORS.FORREST,
  TILE_COLORS.PLAINS,
];

export const TILE_BORDER_WIDTH = 16;

export const STARTING_ROW_TILES = 1;

export const MAX_ROW_TILES = 2;